[package]
name = "image-data"
version = "0.1.0"
authors = ["EtomicBomb <ethan@ethan.ws>"]

[dependencies]
png = "0.12.0"

csv = "1.0.0"

regex = "0.2.11"
lazy_static = "1.0"

serde_derive = "1.0.70"
serde = "1.0.70"
